version: "3"
services:
  client:
    build:
      context: ./client
    restart: always
    container_name: bpms_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - webappnetwork
  api:
    build:
      context: .
    restart: always
    container_name: bpms_api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
      - /api/node_modules
    # depends_on:
    #   - mongodb
    networks:
      - webappnetwork
  # mongodb:
  #   image: mongo
  #   restart: always
  #   container_name: mongodb
  #   volumes:
  #     - ./data-node:/data/db
  #   ports:
  #     - 27017:27017
  #   command: mongod --noauth --smallfiles
  #   networks:
  #     - webappnetwork
networks:
    webappnetwork:
        driver: bridge
          