version: '2'
services:
  web:
    build: .
    container_name: bpms/bpms:1.0.0
    ports:
      - "80:80"
    restart: always
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
      PORT: 80